import './Main.css'
import { assets } from '../../assets/assets';
import { useContext } from 'react';
import { Context } from '../../context/Context';
import Markdown from 'react-markdown'
function Main() {
    const {onSent, recentPrompt,showResult,loading,resultData,setInput,input} = useContext(Context);
    return ( 
        <div className='main'> 
            <div className="nav">
                <p>Ask Me Anything</p>
                <img src={assets.user_icon} alt="" />
            </div>
            <div className="main-container">

                {!showResult?<><div className="greet">
                    <p><span>Hello, User</span></p>
                    <p>Ask Away!</p>
                </div>
                <div className="cards">
                    <div className="card">
                        <p>Suggest beautiful places to see in India</p>
                        <img src={assets.compass_icon} alt="" />
                    </div>
                    <div className="card">
                        <p>Tell me a joke</p>
                        <img src={assets.bulb_icon} alt="" />
                    </div>
                    <div className="card">
                        <p>Write an email to my boss for a leave</p>
                        <img src={assets.message_icon} alt="" />
                    </div>
                    <div className="card">
                        <p>Improve the readability of the following code</p>
                        <img src={assets.code_icon} alt="" />
                    </div>
                </div></>: 
                <div className='result'>
                    <div className="result-title">
                        <img src={assets.user_icon} alt="" />
                        <p>{recentPrompt}</p>
                    </div>
                    <div className="result-data">
                        <img src={assets.gemini_icon} alt="" />
                        {loading?(
                        <div className='loader'>
                            <hr />
                            <hr />
                            <hr />
                        </div>
                        ):(
                            <Markdown>{resultData}</Markdown>
                        )}
                        
                    </div>
                </div>
                }

                
                <div className="main-bottom">
                    <div className="search-box">
                        <input onChange={(e)=>setInput(e.target.value)} value={input} type="text" name="" placeholder='Enter a prompt here' />
                        <div>
                            {input && <img onClick={()=>{onSent()}} src={assets.send_icon} alt="" />}
                        </div>
                    </div>
                    <p className="bottom-info">Responses are generated by Gemini API and may contain inaccuracies or biases.</p>
                </div>
            </div>
        </div>
     );
}


export default Main;